"""Add user bio

Revision ID: 639fbd8c507a
Revises: 803359e373af
Create Date: 2019-09-27 11:16:40.362632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '639fbd8c507a'
down_revision = '803359e373af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###
